[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 24, y = 24 }
opacity = 0.90

[scrolling]
history = 100000

[font]
size = 14.0
normal = { family = "Roboto Mono", style = "Regular" }
bold = { family = "Roboto Mono", style = "Bold" }
italic = { family = "Roboto Mono", style = "Italic" }

[colors]
draw_bold_text_with_bright_colors = true

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\x1b\r"

[selection]
save_to_clipboard = true

[terminal]
shell = { program = "tmux", args = ["new-session", "-A", "-s", "general"] }
